pipelines:
  - name: portfolio_style
    configuration:
      environmentVariables:
        readOnly:
          git_branch: "{{gitBranch}}"
    steps:
      - name: style_build
        type: Bash
        configuration:
          inputResources:
            - name: repoStyle
          runtime:
            type: image
            image:
              custom:
                name: kashyaprahul94-docker.jfrog.io/portfolio-ci
                tag: stable
                registry: kashyaprahul94_docker
                sourceRepository: docker
        execution:
          onExecute:
            - pushd $res_repoStyle_resourcePath
            - yarn --version
            # - yarn --update-checksums
            # - yarn build
            - ls -al
            - popd