pipelines:

  - name: portfolio_style
    configuration:
      runtime:
        type: image
        image:
          custom:
            name: "kashyaprahul94-docker.jfrog.io/portfolio-ci"
            tag: "feature-jfrog-pipelines-001"
            registry: "kashyaprahul94_docker"
            sourceRepository: "docker"
      environmentVariables:
        readOnly:
          GIT_BRANCH: "{{gitBranch}}"
          PACKAGE_NAME: "style"
          NPM_USER_NAME: "service_user"
          NPM_USER_EMAIL: "kashyaprahul94@gmail.com"

    steps:
      - name: style_init
        type: Bash
        configuration:
          integrations:
            - name: kashyaprahul94_npm
          inputResources:
            - name: repoStyle
        execution:
          onStart:
            - pushd $res_repoStyle_resourcePath
            - ./pipelines/init-npmrc.sh $int_kashyaprahul94_npm_RT_NPM_REGISTRY $int_kashyaprahul94_npm_RT_NPM_AUTH $int_kashyaprahul94_npm_RT_NPM_AUTH_EMAIL .
            - add_run_files ./.npmrc state_npmrc

      - name: style_build_and_publish
        type: Bash
        configuration:
          inputResources:
            - name: repoStyle
          inputSteps:
            - name: style_init
        execution:
          onStart:
            - pushd $res_repoStyle_resourcePath/packages/$PACKAGE_NAME
            - restore_run_files state_npmrc ./.npmrc
          onExecute:
            - yarn install --update-checksums
            - yarn compile
            - $( ./pipelines/publish-to-npm.sh $GIT_BRANCH )