pipelines:
  - name: portfolio_ci
    configuration:
      environmentVariables:
        readOnly:
          GIT_BRANCH: "{{gitBranch}}"
          DOCKER_REGISTRY: "kashyaprahul94-docker.jfrog.io"
          DOCKER_IMAGE_NAME_: "portfolio-ci"
          DOCKER_FULL_IMAGE_NAME: "${DOCKER_REGISTRY}/${DOCKER_IMAGE_NAME_}"

    steps:
      - name: ci_entry
        type: Bash
        configuration:
          inputResources:
            - name: repoCI
        execution:
          onStart:
            - printenv
            - pushd $res_repoCI_resourcePath
            - add_run_variables RELEASE_TAG=$( ./pipelines/normalize-version.sh ${GIT_BRANCH} )
            - echo "Release tag will be --> ${RELEASE_TAG}."
            - popd

      - name: ci_docker_build
        type: DockerBuild
        configuration:
          integrations:
            - name: kashyaprahul94_artifactory
          inputResources:
            - name: repoCI
          inputSteps:
            - name: ci_entry
          affinityGroup: group_docker_build_push

          dockerFileLocation: packages/ci
          dockerFileName: Dockerfile
          dockerImageName: "${DOCKER_FULL_IMAGE_NAME}"
          dockerImageTag: ${RELEASE_TAG}
        execution:
          onSuccess:
            - echo "Docker image is built successfully."
            - echo "Image ---> ${DOCKER_FULL_IMAGE_NAME}:${RELEASE_TAG}"

      - name: ci_docker_push_to_jfrog
        type: DockerPush
        configuration:
          integrations:
            - name: kashyaprahul94_artifactory
          inputSteps:
            - name: ci_docker_build
          affinityGroup: group_docker_build_push

          targetRepository: docker
        execution:
          onStart:
            - docker images
          onSuccess:
            - echo "Docker image is pushed to JFrog Docker Registry successfully."
            - echo "Image ---> ${DOCKER_FULL_IMAGE_NAME}:${RELEASE_TAG}"