name: Test

on: [push]

jobs:
  build:
    name: Build | Tag Docker Image | Push Docker Image to Registry
    runs-on: ubuntu-16.04

    steps:
      - uses: actions/checkout@v1

      - name: "Test step"
        uses: ./ci.yml

      - name: "testaaaaaa"
        run: "echo node -v"
