name: Release

on:
  push:
    branches:
      - master
    tags-ignore:
      - "**"

jobs:
  prepare:
    runs-on: ubuntu-latest
    name: Prepare
    if: "! contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: Current commit
        run: echo "Commit ----> ${{ github.event.head_commit.message }}"

  build_release_deploy:
    name: Build | Release NPM Packages | Tag App Docker Image | Push App Docker Image to Registry
    runs-on: ubuntu-latest
    needs: prepare

    steps:
      - name: Install 'Node 10'
        run: sudo npm install -g n && sudo n 10

      - name: Checkout Repository
        uses: "actions/checkout@v1"

      - name: Setup Environment
        run: bash ./pipelines/setup-env.sh

      - name: Reattach HEAD
        run: sudo git checkout $LOCAL_BRANCH

      - name: Install dependencies & Build
        run: bash ./pipelines/install-dependencies-and-build.sh
        env:
          NPM_TOKEN: ${{ secrets.GITHUB_CI_TOKEN }}
          NPM_REGISTRY: npm.pkg.github.com

      - name: Release NPM Packages
        run: bash ./pipelines/publish-to-npm.sh || true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_USERNAME: kashyaprahul94
          GITHUB_REPOSITORY: portfolio
          NPM_TOKEN: ${{ secrets.GITHUB_CI_TOKEN }}
          NPM_REGISTRY: npm.pkg.github.com

      ##### App

      - name: Tag App Docker Image
        run: bash ./pipelines/app/tag-docker-image.sh
        env:
          DOCKER_USERNAME: kashyaprahul94
          REPOSITORY_NAME: portfolio
          DOCKER_IMAGE_NAME: app
          DOCKER_PASSWORD: ${{ secrets.GITHUB_CI_TOKEN }}
          DOCKER_REGISTRY: docker.pkg.github.com

      - name: Publish App Image to Docker Hub
        run: bash ./pipelines/app/publish-to-docker-hub.sh || true
        env:
          DOCKER_USERNAME: kashyaprahul94
          REPOSITORY_NAME: portfolio
          DOCKER_IMAGE_NAME: app
          DOCKER_PASSWORD: ${{ secrets.DOCKER_HUB_CI_TOKEN }}

      - name: Publish App Image to GitHub Registry
        run: bash ./pipelines/app/publish-to-github.sh || true
        env:
          DOCKER_USERNAME: kashyaprahul94
          REPOSITORY_NAME: portfolio
          DOCKER_IMAGE_NAME: app
          DOCKER_PASSWORD: ${{ secrets.GITHUB_CI_TOKEN }}
          DOCKER_REGISTRY: docker.pkg.github.com