name: Pull Request

on:
  pull_request:
    branches:
      - "**"
    tags-ignore:
      - "**"

jobs:
  prepare:
    runs-on: ubuntu-latest
    name: Prepare
    if: "! contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: Current commit
        run: echo "Commit ----> ${{ github.event.head_commit.message }}"

  build_release_deploy:
    name: Build | Tag App Docker Image | Push App Docker Image to Registry
    runs-on: ubuntu-latest
    needs: prepare

    steps:
      - name: Test
        run: "echo $GITHUB_CONTEXT"
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
