name: Portfolio - Style

on:
  push:
    branches:
      - "**"
    paths:
      - "packages/style/**"

jobs:
  build:
    name: Release NPM Packages
    runs-on: ubuntu-16.04

    steps:
      - uses: actions/checkout@v1

      - name: Install dependencies & Build
        run: bash ./pipelines/install-dependencies-and-build.sh
        env:
          NPM_TOKEN: ${{ secrets.GITHUB_CI_TOKEN }}
          NPM_REGISTRY: npm.pkg.github.com

      - name: Release NPM Packages
        run: bash ./pipelines/publish-to-npm.sh
        env:
          NPM_TOKEN: ${{ secrets.GITHUB_CI_TOKEN }}
          NPM_REGISTRY: npm.pkg.github.com
